#!/bin/bash

# Get the directory where the script is located
DIR="$(cd "$(dirname "$0")" && pwd)"

# Launch the JavaFX application
java \
  --module-path "/Users/javiersantana/Java/javafx-sdk-23.0.1/lib" \
  --add-modules javafx.controls,javafx.fxml \
  -jar "/Users/javiersantana/Desktop/Banana_Script/BananaFormFillerApp/target/FormFiller-1.0-SNAPSHOT-jar-with-dependencies.jar"
